### ISSUE TITLE
Stats-related NPE

### ISSUE THREAD

**Issue by bts** [ztellman/dirigiste#1]
With dirigiste 0.1.0-alpha5 (as used by aleph 0.4.0-SNAPSHOT at [5030a05](https://github.com/ztellman/aleph/tree/5030a05e57ac60c23bf687dc12767e486481df40)), I occasionally see a stack trace like the following when doing an `http/get`:

```
Exception in thread "dirigiste-pool-controller-0" java.lang.NullPointerException
	at io.aleph.dirigiste.Stats.lerp(Stats.java:156)
	at io.aleph.dirigiste.Stats.getTaskLatency(Stats.java:355)
	at aleph.flow$stats__GT_map$fn__7585.invoke(flow.clj:37)
	at clojure.core$mapv$fn__6689.invoke(core.clj:6611)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:332)
	at clojure.core$reduce.invoke(core.clj:6513)
	at clojure.core$mapv.invoke(core.clj:6611)
	at aleph.flow$stats__GT_map$q__7579.invoke(flow.clj:29)
	at aleph.flow$stats__GT_map.invoke(flow.clj:37)
	at aleph.flow$stats__GT_map.invoke(flow.clj:26)
	at clojure.core$map$fn__4529.invoke(core.clj:2614)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:485)
	at clojure.core$seq__4109.invoke(core.clj:135)
	at clojure.core$zipmap.invoke(core.clj:2942)
	at aleph.flow$instrumented_pool$reify__7607.adjustment(flow.clj:100)
	at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:359)
	at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
	at io.aleph.dirigiste.Pool$1.run(Pool.java:419)
	at java.lang.Thread.run(Thread.java:745)
```

Looks like `vals` in the `(long[], double)` overloading of `lerp` is sometimes `null` when calculating the task latency:

https://github.com/ztellman/dirigiste/blob/75d4a3f8bab7ef9f23bc77c5b62c9b422f43dce2/src/io/aleph/dirigiste/Stats.java#L156

**Comment by ztellman** [comment]
Hmm, not immediately sure how that's happening, but definitely something that needs fixing.  Thanks for the report.

**Comment by bts** [comment]
I'm now able to reproduce it consistently by making requests to a closed port: `(http/get "https://localhost:54321/")`

**Comment by ztellman** [comment]
Yeah, I figured out the underlying issue. It's an unavoidable race
condition between different sorts of metrics gathering, I just need to be
robust to it. An updated version of Dirigiste and Aleph will be
forthcoming.

**Comment by bts** [comment]
I've run out of time to look into this today but I'll try to take another look tomorrow.

**Comment by bts** [comment]
Awesome! Thanks Zach.

**Comment by ztellman** [comment]
I've cut `0.1.0-alpha6` of Dirigiste, and `0.4.0-beta2` of Aleph.  Thanks again for the report.
